"""
Colunas fixas da Declaração de Óbito (SIM/DATASUS), compartilhadas entre
o process do consolidado e do preliminar -- os dois usam exatamente a
mesma estrutura de colunas.
"""

COLUNAS_DECLARACAO_OBITO = [
    "CONTADOR", "ORIGEM", "TIPOBITO", "DTOBITO", "HORAOBITO", "NATURAL", "CODMUNNATU", "DTNASC", "IDADE", "SEXO",
    "RACACOR", "ESTCIV", "ESC", "ESC2010", "SERIESCFAL", "OCUP", "CODMUNRES", "LOCOCOR", "CODESTAB", "ESTABDESCR",
    "CODMUNOCOR", "IDADEMAE", "ESCMAE", "ESCMAE2010", "SERIESCMAE", "OCUPMAE", "QTDFILVIVO", "QTDFILMORT", "GRAVIDEZ",
    "SEMAGESTAC", "GESTACAO", "PARTO", "OBITOPARTO", "PESO", "TPMORTEOCO", "OBITOGRAV", "OBITOPUERP", "ASSISTMED",
    "EXAME", "CIRURGIA", "NECROPSIA", "LINHAA", "LINHAB", "LINHAC", "LINHAD", "LINHAII", "CAUSABAS", "CB_PRE", "CRM",
    "COMUNSVOIM", "DTATESTADO", "CIRCOBITO", "ACIDTRAB", "FONTE", "NUMEROLOTE", "TPPOS", "DTINVESTIG", "CAUSABAS_O",
    "DTCADASTRO", "ATESTANTE", "STCODIFICA", "CODIFICADO", "VERSAOSIST", "VERSAOSCB", "FONTEINV", "DTRECEBIM",
    "ATESTADO", "DTRECORIGA", "CAUSAMAT", "ESCMAEAGR1", "ESCFALAGR1", "STDOEPIDEM", "STDONOVA", "DIFDATA",
    "NUDIASOBCO", "NUDIASOBIN", "DTCADINV", "TPOBITOCOR", "DTCONINV", "FONTES", "TPRESGINFO", "TPNIVELINV",
    "NUDIASINF", "DTCADINF", "MORTEPARTO", "DTCONCASO", "FONTESINF", "ALTCAUSA"
]